### ISSUE TITLE
RSS Jsoup

### ISSUE THREAD

**Issue by AhmadTakkoush** [AhmadTakkoush/Apple-Developer#1]
News content displays full xml
Only need to select first <p> tag from RSS description

**Comment by shivam21** [comment]
Hi @AhmadTakkoush can you please explain this issue in more detail.

**Comment by AhmadTakkoush** [comment]
@shivam21 Need the news to display just the headline or the headline + description but it needs to take just the <p> content for the description, since now it displays the whole XML of the page it is not readable for users and the text takes too much space from the card.

**Comment by shivam21** [comment]
We can show first paragraph tag from html we are getting in content.
Is this ok with you?

**Comment by AhmadTakkoush** [comment]
Absolutely, that's all I want. Thank you!
